# Generated by Django 6.0.1 on 2026-03-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_repayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
