# Generated by Django 6.0.1 on 2026-03-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_repayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
    ]
